### ISSUE TITLE
Feature discussion: MJViewController addFuture(MJFuture)

### ISSUE THREAD

**Issue by RubenVot** [mobilejazz/MJiOSCore#2]
I think MJViewController should include a method like "addFuture(Future)" which should store a future until the VC is dealloc. 

Maybe a symmetric method like removeFuture(Future) or removeFuture("identifier_key") could be handy too. 

What do you think @vilanovi @mariabernis @joselufo?

**Comment by vilanovi** [comment]
Could you elaborate an example of usage?

**Comment by RubenVot** [comment]
Sure thing! 

Most of the times is related to reactiveFutures. You wan to react to changes in some manager or other screen so you need to keep a reference to a MJReactiveFuture which is by default weak. Also you want this reference to disappear when the ViewController is dealloc so the future is not executing anymore. 

You can just store it as: 

`@property (nonatomic, strong) MJFuture<T> *reactToXChanges;`

and later 

```
-viewDidLoad() {
    _reactToChanges = [objectChanging futureForChanges]; 
    _reacToChanges then {
          // Whatever 
    }]; 
}
```
But, many times in UI you will have half dozen futures so a more generic way to store the futures will be needed. 

Extra point: 
If we had a reactiveThen then we could also write: 
```
-viewDidLoad() {
    self.addFuture([[[objectChanging futureForChanges] reactiveThen:{
        // Do something 
    }]; 
}
```

**Comment by vilanovi** [comment]
You could have just a dictionary and store futures there directly. Not sure if it is worthy to add this to all MJViewController instnaces.
